[package]
name = "advent_20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
lazy_static = "1.4"
num = "0.4"
regex = "1.5"
strum = "0.24"
strum_macros = "0.24"